"""
core/exporters.py — Export Engine.

Converts Protocol objects into formatted output files:
  - PDF via ReportLab
  - DOCX via python-docx
  - XLSX via openpyxl
Each exporter is a pure function: Protocol + file_path → written file.
"""

from __future__ import annotations

import os
from datetime import date
from typing import Optional

from core.models import Protocol, Panel, ExportFormat


# ─── DOCX Export ──────────────────────────────────────────────────────────────

def export_docx(protocol: Protocol, file_path: str) -> bool:
    """Export protocol as a formatted Word document."""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise ImportError("python-docx is required for DOCX export. pip install python-docx")

    doc = Document()

    # Title
    title = doc.add_heading(protocol.title, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta.add_run(
        f"Author: {protocol.author}  |  Lab: {protocol.lab_name}  |  "
        f"Date: {protocol.created_date.isoformat()}  |  Version: {protocol.version}"
    )
    meta_run.font.size = Pt(10)
    meta_run.font.color.rgb = RGBColor(100, 100, 100)

    doc.add_paragraph("")  # Spacer

    # Sections
    for section in sorted(protocol.sections, key=lambda s: s.order):
        doc.add_heading(section.title, level=1)

        # Handle markdown-style tables
        if "|" in section.content and "---" in section.content:
            _add_markdown_table_to_docx(doc, section.content)
        else:
            for paragraph_text in section.content.split("\n"):
                if paragraph_text.strip():
                    p = doc.add_paragraph(paragraph_text)
                    p.paragraph_format.space_after = Pt(4)

    # Footer
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        f"Generated by IF Panel Designer | {date.today().isoformat()}"
    )
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(150, 150, 150)

    doc.save(file_path)
    return True


def _add_markdown_table_to_docx(doc, content: str):
    """Convert a markdown-style table to a Word table."""
    from docx.shared import Pt

    lines = [l.strip() for l in content.split("\n") if l.strip()]

    # Separate table lines from non-table content
    table_lines = []
    non_table_before = []
    non_table_after = []
    in_table = False

    for line in lines:
        if line.startswith("|"):
            in_table = True
            if "---" not in line:  # Skip separator line
                table_lines.append(line)
        elif in_table:
            non_table_after.append(line)
        else:
            non_table_before.append(line)

    # Add non-table content before
    for text in non_table_before:
        if text.strip():
            doc.add_paragraph(text)

    # Add table
    if table_lines:
        # Parse cells
        rows_data = []
        for line in table_lines:
            cells = [c.strip() for c in line.strip("|").split("|")]
            rows_data.append(cells)

        if rows_data:
            num_cols = len(rows_data[0])
            table = doc.add_table(rows=len(rows_data), cols=num_cols)
            table.style = "Table Grid"

            for i, row_data in enumerate(rows_data):
                for j, cell_text in enumerate(row_data):
                    if j < num_cols:
                        cell = table.cell(i, j)
                        cell.text = cell_text
                        for paragraph in cell.paragraphs:
                            for run in paragraph.runs:
                                run.font.size = Pt(9)

    # Add non-table content after
    for text in non_table_after:
        if text.strip():
            doc.add_paragraph(text)


# ─── PDF Export ───────────────────────────────────────────────────────────────

def export_pdf(protocol: Protocol, file_path: str) -> bool:
    """Export protocol as a PDF document."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            PageBreak,
        )
    except ImportError:
        raise ImportError("reportlab is required for PDF export. pip install reportlab")

    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='SectionHeading',
        parent=styles['Heading1'],
        fontSize=14,
        spaceAfter=10,
        textColor=HexColor('#2C3E50'),
    ))
    styles.add(ParagraphStyle(
        name='ProtocolBody',
        parent=styles['Normal'],
        fontSize=10,
        spaceAfter=6,
        leading=14,
    ))
    styles.add(ParagraphStyle(
        name='ProtocolTitle',
        parent=styles['Title'],
        fontSize=18,
        textColor=HexColor('#1A5276'),
    ))

    story = []

    # Title
    story.append(Paragraph(protocol.title, styles['ProtocolTitle']))
    story.append(Spacer(1, 12))

    # Metadata
    meta_text = (
        f"<b>Author:</b> {protocol.author} &nbsp;|&nbsp; "
        f"<b>Lab:</b> {protocol.lab_name} &nbsp;|&nbsp; "
        f"<b>Date:</b> {protocol.created_date.isoformat()} &nbsp;|&nbsp; "
        f"<b>Version:</b> {protocol.version}"
    )
    story.append(Paragraph(meta_text, styles['Normal']))
    story.append(Spacer(1, 20))

    # Sections
    for section in sorted(protocol.sections, key=lambda s: s.order):
        story.append(Paragraph(section.title, styles['SectionHeading']))

        # Convert content to paragraphs
        for line in section.content.split("\n"):
            if line.strip():
                # Escape XML special chars
                safe_line = (
                    line.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
                )
                story.append(Paragraph(safe_line, styles['ProtocolBody']))

        story.append(Spacer(1, 12))

    doc.build(story)
    return True


# ─── Excel Export ─────────────────────────────────────────────────────────────

def export_xlsx(protocol: Protocol, file_path: str) -> bool:
    """Export reagent table and cost summary as an Excel workbook."""
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    except ImportError:
        raise ImportError("openpyxl is required for Excel export. pip install openpyxl")

    wb = Workbook()

    # Sheet 1: Reagent Table
    ws1 = wb.active
    ws1.title = "Reagent Table"

    headers = [
        "Target", "Antibody", "Host Species", "Clone", "Conjugate",
        "Dilution", "Catalog #", "Vendor", "Lot #", "Channel", "Fluorophore"
    ]

    # Header styling
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="2C3E50", end_color="2C3E50", fill_type="solid")
    thin_border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin'),
    )

    for col, header in enumerate(headers, 1):
        cell = ws1.cell(row=1, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center')
        cell.border = thin_border

    # Data rows
    if protocol.panel:
        for row_idx, target in enumerate(protocol.panel.targets, 2):
            primary = target.primary
            data = [
                target.target_name,
                f"Anti-{target.target_name}" if primary else "",
                primary.host_species.value if primary else "",
                primary.clone_name if primary else "",
                primary.conjugate if primary else "",
                primary.dilution if primary else "",
                primary.catalog_no if primary else "",
                primary.vendor if primary else "",
                primary.lot_no if primary else "",
                target.channel or "",
                target.fluorophore or "",
            ]
            for col, value in enumerate(data, 1):
                cell = ws1.cell(row=row_idx, column=col, value=value)
                cell.border = thin_border

    # Auto-fit column widths
    for col in ws1.columns:
        max_length = 0
        column_letter = col[0].column_letter
        for cell in col:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        ws1.column_dimensions[column_letter].width = min(max_length + 4, 30)

    # Sheet 2: Controls
    ws2 = wb.create_sheet("Controls")
    ctrl_headers = ["#", "Control Type", "Purpose", "Preparation", "Required"]
    for col, header in enumerate(ctrl_headers, 1):
        cell = ws2.cell(row=1, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.border = thin_border

    for row_idx, ctrl in enumerate(protocol.controls, 2):
        data = [
            row_idx - 1,
            ctrl.control_type,
            ctrl.purpose,
            ctrl.preparation,
            "Yes" if ctrl.is_required else "No",
        ]
        for col, value in enumerate(data, 1):
            cell = ws2.cell(row=row_idx, column=col, value=value)
            cell.border = thin_border

    for col in ws2.columns:
        max_length = 0
        column_letter = col[0].column_letter
        for cell in col:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))
        ws2.column_dimensions[column_letter].width = min(max_length + 4, 50)

    wb.save(file_path)
    return True


# ─── Unified Export Function ──────────────────────────────────────────────────

def export_protocol(
    protocol: Protocol,
    file_path: str,
    format: ExportFormat = ExportFormat.DOCX,
) -> bool:
    """Export a protocol in the specified format."""
    os.makedirs(os.path.dirname(file_path) or ".", exist_ok=True)

    if format == ExportFormat.DOCX:
        return export_docx(protocol, file_path)
    elif format == ExportFormat.PDF:
        return export_pdf(protocol, file_path)
    elif format == ExportFormat.XLSX:
        return export_xlsx(protocol, file_path)
    else:
        raise ValueError(f"Unsupported export format: {format}")
